version: "3"

services:           
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/config:/data/configdb
    ports:
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"

  metabase:
    container_name: metabase
    image: metabase/metabase:latest
    environment:
      - MB_DB_FILE=/tmp/metabase.db
    volumes:
      - ./mongo/metabase:/tmp
    ports:
      - "3000:3000"

  python:
    container_name: python
    image: python_cmdb:latest
    command: start-notebook.sh --NotebookApp.token=''
    ports:
      - "8888:8888"
    volumes:
      - "./notebooks:/notebooks" 
      - "./data:/data"

  web:
    # app is running at: http://localhost:8080/CMDB/homePage.html
    container_name: web
    image: tomcat:latest
    command: catalina.sh run
    ports: 
      - "8080:8080"
    volumes:
      - ./web/app/CMDB.war:/usr/local/tomcat/webapps/CMDB.war
      - ./web/app/logs/:/usr/local/tomcat/logs/
    depends_on:
      - mongo

  splunk:
    container_name: splunk
    image: splunk/splunk:latest
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes 
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_ADD: tcp 1514
      SPLUNK_PASSWORD: 12345678
    volumes:
      - ./splunk/etc:/opt/splunk/etc
      - ./splunk/var:/opt/splunk/var
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "8089:8089"
      - "1514:1514"
    restart: always

  pyflow:
    container_name: pyflow
    image: pyflow_cmdb:latest
    ports:
      - "5000:5000"

